### ISSUE TITLE
installer: make it run on red hat

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#112]
Installation documented here: <https://github.com/CactuseSecurity/firewall-orchestrator/blob/master/documentation/developer-docs/ansible-redhat.md>

- [x] download from <https://developers.redhat.com/products/rhel/download>
- [x] install minimal server - do not select "connect to red hat insight"
- [x] do test install
- [ ] fix all issues during installation

- see also <https://www.heise.de/news/Kostenloses-RHEL-statt-CentOS-5030972.html>
- main issue is to know the package names per distribution
- other issues include name and location of Linux Distribution dependent config files
- package updates/upgrades (apt update, apt upgrade) will have to be handled with when statements per OS
- replace all apt module occurences with package module:
   bad:
```
     - name: Install packages for docker download n installation
       apt:
         name: "{{ packages }}"
       vars:
         packages:
         - gnupg2
```

  good:
```
   - name: Install packages for python pip3 n virtualenv
     package:
        name: "{{ packages }}"
     vars:
        packages:
          - python3-pip
          - python3-virtualenv
```

- need to add further case distinctions like
```
          when: ansible_facts['distribution'] == "Ubuntu"
          when: ansible_facts['distribution'] == "Debian"

```
