### ISSUE TITLE
OpenLdap upgrade script not robust enough

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#2269]
in roles/middleware/tasks/upgrade_ldif_file.yml
```yaml
- name: calling upgrade_modify_routine
  include_tasks: upgrade_modify_routine.yml
  loop: "{{ ldif_list[1:] }}"
```

This always ignores the first lines before first dn
need to make this more robust for files that start with dn: line
