### ISSUE TITLE
Automate release note generation

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#2986]
can we add all included PR texts automatically into a release note?

**Comment by tpurschke** [comment]
we will for the time being simply use the github auto generation 

Steps:

1. Go to the Releases page of your repository.
2. Click Draft a new release.
3. Under "Generate release notes," click Generate release notes.
4. GitHub will automatically pull in merged PRs and issues related to this release.
5. Modify if needed and publish.

Also think about automation

```yaml
name: Create Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate release notes
        run: gh release create ${{ github.ref_name }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
